field:
  name:
    - nl_NL: Naam
    - en_EN: Name
  label:
    - nl_NL: Voornaam en achternaam
    - en_EN: First name and last name
  type: TextInput
  handle: name
  form:
    all:
      trim: true
