field:
  name:
    - nl_NL: Titel
    - en_EN: Title
  label:
    - nl_NL: Titel
    - en_EN: Title
  handle: title
  type: TextInput
  form:
    all:
      trim: true
    update:
      disabled: true
  generator:
    entity:
      validator:
        Length:
          min: 2
          max: 255
    doctrine:
      length: 255
