field:
  name:
    - nl_NL: Slug
    - en_EN: Slug
  handle: slug
  label:
    - nl_NL: Onderdeel voor url segment
    - en_EN: Composit for url segment
  type: Slug
  length: 255 #move to generator->doctrine config
  typeConfig: [ title, created|DateTime|Y-m-d ] #move to generator config
  generator:
    entity:
      slugFields: [ title, created|DateTime|Y-m-d ]
    doctrine:
      length: 255
      unique: true
  form:
    default:
      available: false
