field:
  name:
    - nl_NL: Auteur slug
    - en_EN: Author slug
  handle: authorSlug
  label:
    - nl_NL: Onderdeel voor url segment
    - en_EN: Composit for url segment
  type: Slug
  generator:
    entity:
      slugFields: [ name ]
    doctrine:
      length: 255
      unique: true
  form:
    all:
      available: false
