field:
  name:
    - nl_NL: Auteur
    - en_EN: Author
  handle: blogAuthor
  label:
    - nl_NL: Auteur van blog
    - en_EN: Author that wrote blog
  type: Relationship
  variant: select
  kind: many-to-many
  relationship-type: bidirectional
  to: blog
