field:
  name:
    - nl_NL: Blog
    - en_EN: Blog
  handle: blog
  label:
    - nl_NL: Relatie tot blog
    - en_EN: Relationship to blog
  type: Relationship
  variant: hidden
  kind: many-to-one
  to: blog
