section:
  name: Many to Many - 1
  handle: mtm1
  fields:
    - title
    - toTwo
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
