section:
  name: Many to Many - 2
  handle: mtm2
  fields:
    - title
    - toOne
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
