section:
  name: Many to One - One
  handle: mtoOne
  fields:
    - title
    - slug
    - updated
    - created
  default: title
  created: created
  updated: updated
  slug: slug
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
