section:
  name: One to Many - One
  handle: otmOne
  fields:
    - title
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
