section:
  name: One to Many - Many
  handle: otmMany
  fields:
    - title
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
