section:
  name: One to One - 2
  handle: oto2
  fields:
    - title
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
