section:
  name: One to One - 1
  handle: oto1
  fields:
    - title
    - slug
    - updated
    - created
  default: title
  namespace: Example\Relationships
  generator:
    entity:
      title:
        NotBlank: ~
