generator:
  entity:
    - properties: Tardigrades\FieldType\Generator\EntityPropertiesGenerator
      methods: Tardigrades\FieldType\Generator\EntityMethodsGenerator
  doctrine:
    - manyToOne: Tardigrades\FieldType\Relationship\Generator\DoctrineManyToOneGenerator
      oneToMany: Tardigrades\FieldType\Relationship\Generator\DoctrineOneToManyGenerator
      oneToOne: Tardigrades\FieldType\Relationship\Generator\DoctrineOneToOneGenerator
      manyToMany: Tardigrades\FieldType\Relationship\Generator\DoctrineManyToManyGenerator
