generator:
  entity:
    properties: Tardigrades\FieldType\Relationship\Generator\EntityPropertiesGenerator
    methods: Tardigrades\FieldType\Relationship\Generator\EntityMethodsGenerator
    constructor: Tardigrades\FieldType\Relationship\Generator\EntityConstructorGenerator
  doctrine:
    manyToOne: Tardigrades\FieldType\Relationship\Generator\DoctrineManyToOneGenerator
    oneToMany: Tardigrades\FieldType\Relationship\Generator\DoctrineOneToManyGenerator
    oneToOne: Tardigrades\FieldType\Relationship\Generator\DoctrineOneToOneGenerator
    manyToMany: Tardigrades\FieldType\Relationship\Generator\DoctrineManyToManyGenerator
