section:
  name: Comment
  handle: comment
  fields:
    - name
    - email
    - comment
    - blog
  required:
    - name
    - email
    - comment
    - blog
  default: name
  namespace: Example\Blog
