rest.section.all:
  path: /v1/section/{sectionHandle}/{offset}/{limit}/{orderBy}/{sort}
  defaults: { _controller: 'rest.controller:getEntries', offset: '0', limit: '10', orderBy: '', sort: 'DESC' }
  requirements:
    offset: '\d+'
    limit: '\d+'
  methods:  [GET]

rest.section.info:
  path: /v1/section/{sectionHandle}
  defaults: { _controller: 'rest.controller:getSectionInfo' }
  methods: [OPTIONS]

rest.section.entry.by.id:
  path: /v1/section/{sectionHandle}/{id}
  defaults: { _controller: 'rest.controller:getEntryById' }
  requirements:
    id: '\d+'
  methods:  [GET]

rest.section.entry.by.slug:
  path: /v1/section/{sectionHandle}/{slug}
  defaults: { _controller: 'rest.controller:getEntryBySlug' }
  methods:  [GET]

rest.section.create:
  path: /v1/section/{sectionHandle}
  defaults: { _controller: 'rest.controller:createEntry' }
  methods: [POST]
