section:
  name: Author
  handle: author
  fields:
    - name
    - birthdate
    - authorSlug
    - blogAuthor
    - created
    - updated
  slug: authorSlug
  default: name
  namespace: Example\Blog
  generator:
    entity:
      name:
        NotBlank: ~
