section:
  name: Blog
  handle: blog
  fields:
    - title
    - subTitle
    - body
    - blogSlug
    - authorBlog
    - created
    - updated
  slug: blogSlug # assign the field that will function as slug
  created: created # assign the field that will function as created date
  updated: updated # assign the field that will function as updated date
  default: title
  namespace: Example\Blog
  generator:
    entity:
      title:
        NotBlank: ~
      body:
        NotBlank: ~
