section:
  name: Comment
  handle: comment
  fields:
    - name
    - email
    - comment
    - blog
  default: name
  namespace: Example\Blog
  form:
    required:
      - name
      - email
      - comment
      - blog
  generator:
    entity:
      name:
        NotBlank: ~
      comment:
        NotBlank: ~
